export const SHOP = {
  name: "Ayira Mini Mart",
  domain: "ayira-mini-mart-3.myshopify.com",
  location: "Al Khor, Qatar",
  currency: "QAR",
  announcement: "Free delivery in Al Khor on orders over QAR 50",
  announcement_alt: "Same-day delivery, 7 days a week",
  announcement_promo: "Save 15% on your first order — code AYIRA15",
  collections: [
    { handle: "soft-drinks", title: "Soft Drinks", description: "Carbonated soft drinks, sodas and fizzy beverages.", product_count: 10, image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=500", featured: true },
    { handle: "juice", title: "Juice", description: "Fresh juices and fruit drinks.", product_count: 10, image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=500", featured: true },
    { handle: "water", title: "Water", description: "Mineral water and hydration drinks.", product_count: 10, image: "https://images.unsplash.com/photo-1548839140-29a749e1bc4c?q=80&w=500", featured: false },
    { handle: "chocolates-1", title: "Chocolates", description: "Chocolate bars, boxes and confectionery.", product_count: 10, image: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=500", featured: true },
    { handle: "candy", title: "Candy", description: "Sweets, candies and confectionery.", product_count: 10, image: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?q=80&w=500", featured: false },
    { handle: "gums", title: "Gums", description: "Chewing gums and mints.", product_count: 10, image: "https://images.unsplash.com/photo-1499557408711-2eb26177bbed?q=80&w=500", featured: false },
    { handle: "ice-cream-1", title: "Ice Cream", description: "Browse our range of ice cream and frozen desserts.", product_count: 10, image: "https://images.unsplash.com/photo-1570197571499-166b36435e9f?q=80&w=500", featured: true },
    { handle: "noodles", title: "Noodles", description: "Instant noodles, ramen and quick meals.", product_count: 10, image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?q=80&w=500", featured: true },
    { handle: "dairy", title: "Dairy", description: "Milk, yogurt, cheese, butter, cream and laban.", product_count: 0, image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=500", featured: false },
  ],
  products: [
    { handle: "mountain-dew", title: "Mountain Dew", type: "Soft Drinks", price: 2.00, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400", options: { Size: ["2.25L", "1.25L", "330ml", "150ml"] }, collection: "soft-drinks", sourcing: "PepsiCo · Bottled in Saudi Arabia" },
    { handle: "mirinda-orange", title: "Mirinda Orange", type: "Soft Drinks", price: 2.00, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400", options: { Size: ["1.25L", "330ml", "150ml", "2.25L"] }, collection: "soft-drinks" },
    { handle: "coca-cola-original-taste", title: "Coca-Cola Original Taste", type: "Soft Drinks", price: 2.50, compareAt: null, available: true, badges: ["new"], image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400", options: { Size: ["350ml", "330ml", "250ml", "2.25L"] }, collection: "soft-drinks" },
    { handle: "pepsi", title: "Pepsi", type: "Soft Drinks", price: 2.50, compareAt: 4.50, available: true, badges: ["sale"], image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400", options: { Size: ["1.25L", "330ml", "2.25L"] }, collection: "soft-drinks" },
    { handle: "7up", title: "7Up", type: "Soft Drinks", price: 2.00, compareAt: null, available: false, badges: [], image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400", options: { Size: ["330ml", "150ml"] }, collection: "soft-drinks" },
    { handle: "sprite-lemon-lime-flavoured", title: "Sprite Lemon Lime", type: "Soft Drinks", price: 3.00, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400", options: { Size: ["350ml", "2.25L"] }, collection: "soft-drinks" },
    { handle: "barbican-strawberry-flavour", title: "Barbican Strawberry", type: "Soft Drinks", price: 3.00, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400", options: { Size: ["250ml", "330ml"] }, collection: "soft-drinks" },
    { handle: "kdd-cocktail-fruit-drink", title: "KDD Cocktail Fruit Drink", type: "Juice", price: 1.25, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=400", options: { Size: ["250ml", "180ml", "125ml"] }, collection: "juice" },
    { handle: "kdd-mango-nectar", title: "KDD Mango Nectar", type: "Juice", price: 1.25, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=400", options: { Size: ["250ml", "125ml"] }, collection: "juice" },
    { handle: "pran-frooto-mango-juice", title: "Pran Frooto Mango Juice", type: "Juice", price: 1.00, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=400", options: { Size: ["200ml", "500ml"] }, collection: "juice" },
    { handle: "airwaves-chewing-gum", title: "Airwaves Chewing Gum", type: "Gums", price: 2.50, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1499557408711-2eb26177bbed?q=80&w=400", options: { Size: ["46 pcs", "40 pcs", "14g"] }, collection: "gums" },
    { handle: "galaxy-vanilla-ice-cream", title: "Galaxy Vanilla Ice Cream", type: "Ice Cream", price: 4.50, compareAt: 6.00, available: true, badges: ["sale"], image: "https://images.unsplash.com/photo-1570197571499-166b36435e9f?q=80&w=400", options: { Size: ["59g", "50g"] }, collection: "ice-cream-1" },
    { handle: "snickers-ice-cream", title: "Snickers Ice Cream Bar", type: "Ice Cream", price: 7.00, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1570197571499-166b36435e9f?q=80&w=400", options: { Size: ["70g", "73.5g"] }, collection: "ice-cream-1" },
    { handle: "snickers-chocolate-bar", title: "Snickers Chocolate Bar", type: "Chocolates", price: 3.00, compareAt: null, available: true, badges: [], image: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=400", options: { Size: ["40g", "45g"] }, collection: "chocolates-1" },
  ],
  mainMenu: [
    { title: "Home", url: "/" },
    { title: "Beverages", url: "#", children: [
      { title: "Soft Drinks", url: "/collections/soft-drinks" },
      { title: "Juice", url: "/collections/juice" },
      { title: "Water", url: "/collections/water" },
    ]},
    { title: "Snacks & Sweets", url: "#", children: [
      { title: "Chocolates", url: "/collections/chocolates-1" },
      { title: "Candy", url: "/collections/candy" },
      { title: "Gums", url: "/collections/gums" },
    ]},
    { title: "Frozen", url: "#", children: [
      { title: "Ice Cream", url: "/collections/ice-cream-1" },
    ]},
    { title: "Food", url: "#", children: [
      { title: "Noodles", url: "/collections/noodles" },
    ]},
    { title: "Contact Us", url: "/pages/contact-us" },
  ],
  footerMenu: [
    { title: "Search", url: "/search" },
    { title: "About Us", url: "/pages/about" },
    { title: "Contact Us", url: "/pages/contact-us" },
    { title: "FAQ", url: "/pages/faq" },
    { title: "Shipping & Delivery", url: "/pages/shipping" },
    { title: "Return & Refund Policy", url: "/pages/returns" },
    { title: "Privacy Policy", url: "/pages/privacy" },
    { title: "Terms of Service", url: "/pages/terms" },
  ],
};

export const fmtPrice = (n: number) => `QAR ${Number(n).toFixed(2)}`;
